[project]
name = "peristalsissnn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "gymnasium>=1.1.1",
    "spikingjelly>=0.0.0.0.14",
]
